version: '{build}'
configuration: Release

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release

after_test:
- dotnet pack Argument --configuration Release --output ..

artifacts:
- path: '*.nupkg'

deploy:
- provider: NuGet
  artifact: /.*\.nupkg/
  on:
    branch: /master/
  api_key:
    secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo