version: '{build}'
configuration: Release
image: Visual Studio 2019 Preview

install:
- ps: |-
    choco install dotnetcore-sdk --version 3.0.100-preview7-012821 --pre

cache:
- C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\vcredist140 -> .appveyor.yml
- C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\dotnetcore-sdk -> .appveyor.yml

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release

after_test:
- dotnet pack Argument --configuration Release --output .

artifacts:
- path: '*.nupkg'

deploy:
- provider: NuGet
  artifact: /.*\.nupkg/
  on:
    branch: /master/
  api_key:
    secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo