version: '{build}'
os: Visual Studio 2015
configuration: Release
environment:
  DNX_FEED: https://www.nuget.org/api/v2
install:
- cmd: dnvm upgrade
before_build:
- cmd: dnu restore
build:
  project: Argument.sln
  verbosity: minimal
after_build:
- ps: >-
    Set-StrictMode -Version 2

    $ErrorActionPreference = 'Stop'


    dnx --project Argument.Tests test

    if ($LastExitCode -ne 0) { exit $LastExitCode }
    
    

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\artifacts\Argument.Tests.Results.xml))
test: off
deploy:
- provider: NuGet
  api_key:
    secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo
  on:
    branch: /master|dnx/