name: 'Build / Publish'
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 3.1.x
    
    - run: dotnet build --configuration Release
    - run: dotnet test --no-build --configuration Release
    - run: dotnet pack --no-build --output . --configuration Release

    - run: dotnet nuget push Argument.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
      if: github.ref == 'refs/heads/master'
    
    - uses: actions/upload-artifact@v2
      with:
        path: Argument.nupkg